version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  receiver-service:
    build: ./receiver-service
    ports:
      - "3000:3000"
    environment:
      SQS_QUEUE_URL: ${SQS_QUEUE_URL} # SQS_QUEUE_URL is an environment variable
    depends_on:
      - mongo

  listener-service:
    build: ./listener-service
    environment:
      SQS_QUEUE_URL: ${SQS_QUEUE_URL} 
    depends_on:
      - mongo

volumes:
  mongo-data: